# Generated by Django 3.2.8 on 2021-11-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageID', models.CharField(max_length=256)),
                ('sender', models.CharField(max_length=256)),
                ('timestamp', models.CharField(max_length=64)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
