# Generated by Django 3.2.8 on 2021-11-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isImage',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
