# Generated by Django 3.2.8 on 2021-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_alter_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicPath',
            field=models.TextField(default='https://i.imgur.com/TmnuTk2.png'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=256),
        ),
    ]
