# Generated by Django 3.2.8 on 2021-11-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20211108_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Friendship',
        ),
    ]
