# Generated by Django 3.0.3 on 2021-11-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_rename_friend_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.User'),
        ),
        migrations.CreateModel(
            name='EmojiReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=64)),
                ('emoji', models.CharField(max_length=4)),
                ('messageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.User')),
            ],
        ),
    ]
