# Generated by Django 3.0.3 on 2021-11-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20211111_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojireaction',
            name='emojiReactionID',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
