# Generated by Django 3.0.3 on 2021-11-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_emojireaction_emojireactionid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'timestamp', 'ordering': ['timestamp', 'sender']},
        ),
    ]
